openapi: 3.0.3
info:
  title: Vehicle Export API
  version: 1.0.0

x-amazon-apigateway-binary-media-types:
  - multipart/mixed
  - image/png
  - image/jpeg
  - application/octet-stream
  - application/pdf

paths:
  /vehicle/export:
    get:
      summary: Export vehicle JSON and image
      operationId: getVehicleExport
      responses:
        '200':
          description: Multipart with JSON and image
          content:
            multipart/mixed:
              schema:
                type: object
                properties:
                  garagedVehicle:
                    type: object
                  vehicleImage:
                    type: string
                    format: binary
              encoding:
                garagedVehicle:
                  contentType: application/json
                vehicleImage:
                  contentType: image/png

      x-amazon-apigateway-integration:
        type: http                # 👈 NOT http_proxy
        httpMethod: GET
        uri: http://your-ecs-or-nlb-endpoint/vehicle/export
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_BINARY  # 👈 Critical for raw binary
        responses:
          default:
            statusCode: 200
